### ISSUE TITLE
Yoo! Its the hundredth one

### ISSUE THREAD

**Issue by PSGitHubUser1** [koeqaife/hyprland-material-you#100]
Yay! Its the #100 issue on this repo 

By the way, did you just make a better ChromeOS ? Like HOW!? 

Bro, you need to sleep! You overcooked it.

**Comment by koeqaife** [comment]
Hahahaha, by the way, when I was programming this, I didn’t even think about ChromeOS

**Comment by koeqaife** [comment]
> > Hahahaha, by the way, when I was programming this, I didn’t even think about ChromeOS
> 
> Lol means you created a better chromeOS without knowing

hahha
