### ISSUE TITLE
How to uninstall ?

### ISSUE THREAD

**Issue by yannfill** [koeqaife/hyprland-material-you#101]
Hello,

I tried to rollback all changes, I restored GTK3 and GTK4 ~/.config files, switched back to light theme in Firefox but I style have dark right-click menu and tooltips, and other GTK apps still use dark theme.

Can you provide a script that undo all changes ?

**Comment by koeqaife** [comment]
Try changing the theme in nwg-look

**Comment by yannfill** [comment]
It worked, thanks. I had to apply some gsettings too.
