### ISSUE TITLE
An uninstaller of dotfile or guide

### ISSUE THREAD

**Issue by PSGitHubUser1** [koeqaife/hyprland-material-you#104]
I now want my Arch only on OpenBox, not hyprland or else.

So how do I properly remove all packages and do not corrupt my Arch then end up reinstalling Arch like I always do, it wastes time.

Edit: I don't hate your dotfile, it's good but doesn't fulfill my needs.

**Comment by koeqaife** [comment]
remove links to ags, alacritty, hypr and swappy in ~/.config, also remove the gtk-3.0 and gtk-4.0 folders there. Run `systemctl --user disable --now wl-gammarelay.service` and delete the file `~/.config/systemd/user/wl-gammarelay.service`. With sddm you have to delete the config, I don't remember what to do there. If you installed the theme on Vencord, then delete QuickCSS there. And remove packages you don't need, in install.sh script find the line with installing packages.
