### ISSUE TITLE
Missing Emojis

### ISSUE THREAD

**Issue by dannyrurser** [koeqaife/hyprland-material-you#110]
#### Hey, the problem is just the missing emojis, could someone help me?

![screenshot-20240925-171116](https://github.com/user-attachments/assets/78439209-cb5c-4e60-9af0-3c32cf9d384a)

**Comment by koeqaife** [comment]
This is not a configuration issue, you need to configure the color emoji in your arch linux.

**Comment by dannyrurser** [comment]
thanks
