### ISSUE TITLE
So many issues, where to begin.

### ISSUE THREAD

**Issue by maxfinnsjo** [koeqaife/hyprland-material-you#112]
No bar shows up after install, reboot. Issues during install with cursors, as per usual, whats up with that? ctgen missing? 

Seems like bindings are wonky, why? 

Some serious issues with this install script. 

Looks good, wish I could use it.

**Comment by koeqaife** [comment]
Try running the installation script again

**Comment by maxfinnsjo** [comment]
Didn't miss any steps. Have run it twice already. Will give it nother go and a more detailed log. Thanks for reply, sorry my comment was a bit snarky and lacking in info. I'll remedy that, relly want to try these dots out properly. Thanks.
