### ISSUE TITLE
AGS not started

### ISSUE THREAD

**Issue by bigbabyboost** [koeqaife/hyprland-material-you#116]
Ags can't started, manually run from terminal only show 1 line logs. I try with another ags conf (end4) it's run properly.

This is the log

`(com.github.Aylur.ags:36771): Gjs-Console-CRITICAL **: 07:18:55.241:`

**Comment by koeqaife** [comment]
🤔🤔 I think it's ags problem

**Comment by bigbabyboost** [comment]
> 🤔🤔 I think it's ags problem

I tnink ags problem on arch only, tried with fedora works fine

**Comment by koeqaife** [comment]
> yeah can you check on it please? I just installed it and same error ags is already running but nothing appearing on screen

Everything works for me
