### ISSUE TITLE
Keybindings does not respond at all

### ISSUE THREAD

**Issue by MrVohi** [koeqaife/hyprland-material-you#121]
Hey, just installed your dotfiles on a fresh arch install.
Everything worked great until I noticed that the keybindings don't work at all.

I've tried in an french azerty layout (some keybinds should have worked) and the default qwerty (us) layout but no keybinds worked

That's weird and I can't see what causes the problem,
Any idea? 

Ps: The zip files contains the conf files, in case something made it broke and I don't see it

[hypr_conf.zip](https://github.com/user-attachments/files/17351646/hypr_conf.zip)

**Comment by koeqaife** [comment]
idk why it isn't working

**Comment by MrVohi** [comment]
Well, I'll try rewriting keybinds in a new conf file and I'll see what it does

**Comment by MrVohi** [comment]
Welp, the issue solved itself when I made modifications to hyprland.conf, seems like hyprland has never taken into account the changes until the conf was reloaded.

Anyway, I'll mark the issue has resolved
