### ISSUE TITLE
Hyprlock config

### ISSUE THREAD

**Issue by nullbyto** [koeqaife/hyprland-material-you#13]
Actual Hyprlock config missing in .config/hypr/, there is only a source to a file in .cache

**Comment by koeqaife** [comment]
Try 
ln -s ~/dotfiles/hypr ~/.config/hypr
python ~/dotfiles/material-colors/generate.py --color "#000000"

**Comment by koeqaife** [comment]
and hyprlock config in dotfiles/material-colors/templates

**Comment by nullbyto** [comment]
Thank you!
