### ISSUE TITLE
Bar.ts not loading

### ISSUE THREAD

**Issue by AryA-65** [koeqaife/hyprland-material-you#133]
So when I leave my computer and come back, and log back into the session, my apps are all closed and the navbar (bar.ts) doesn't work for some reason. Everything else works though. Dunno what the problem could be, as I have checked all the files that I though might be related to the problem but to no avail.

**Comment by AryA-65** [comment]
So I tried `killall ags` and then `ags bar` and the session loads back, but I cannot ^C out or it will close the bar.
![image](https://github.com/user-attachments/assets/afd410e2-52ba-46e0-9891-be12b99dc0b2)

**Comment by koeqaife** [comment]
Idk why there're so many errors but you can run `ags & disown` and then close terminal
