### ISSUE TITLE
Issue with decoration.conf file - config option does not exist

### ISSUE THREAD

**Issue by Acebasein** [koeqaife/hyprland-material-you#134]
I'm getting **config option does not exist error** for the following variables in the **decoration.conf** file after a recent system upgrade.

   drop_shadow = true
    shadow_range = 10
    shadow_render_power = 3
    col.shadow = 0x66000000

I don't see these variables in `https://wiki.hyprland.org/Configuring/Variables/ `page. However, wondering why it was not throwing any error earlier. Started receiving this error message after I updated my system yesterday.

**Comment by koeqaife** [comment]
mb hyprland was updated. I'll check it later

**Comment by Acebasein** [comment]
Updated as below and it's working now:

`shadow {
        enabled = true
        range = 10
        render_power = 3
        color = 0x66000000
    }`
