### ISSUE TITLE
Missing types/service/notifications

### ISSUE THREAD

**Issue by Madcliff** [koeqaife/hyprland-material-you#136]
So, was wandering why I didn't seem to be receiving any notifications. Then noticed that the module does not import the notification service, but instead references a non-existent file 

import { Notification as NotificationType } from "types/service/notifications";

Not sure if this is a bug, but it certainly does seem particular to me.

**Comment by koeqaife** [comment]
Uninstall ags and then install https://github.com/kotontrion/PKGBUILDS/blob/main/agsv1/PKGBUILD and then make a link `ln /usr/bin/agsv1 /usr/bin/ags`

**Comment by koeqaife** [comment]
I fixed it in last commit
