### ISSUE TITLE
Error while installing Microtex 

### ISSUE THREAD

**Issue by DynamisOp** [koeqaife/hyprland-material-you#137]
So it goes something like this 

"We are working with GTK on a Unix like OS

Checking for module 'gtksourceviewmm-3.0'

Package 'gtksourceviewmm-3.0', required by 'virtual: world', not found

CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:645 (message):

The following required packages were not found:

gtksourceviewmm-3.0

Call Stack (most recent call first):

/usr/share/cmake/Modules/FindPkgConfig.cmake: 873 (_pkg_check_modules_internal)

CMakeLists.txt:215 (pkg_check_modules)

-- Configuring incomplete, errors occurred!

> ERROR: A failure occurred in build()-

Aborting.

Command failed with exit code 4."

Idk where can i get that package

**Comment by koeqaife** [comment]
> The following required packages were not found:  
> gtksourceviewmm-3.0

**Comment by DynamisOp** [comment]
> > The following required packages were not found:
> > gtksourceviewmm-3.0

Where can i get this package 
I ran the script 3-4 times

**Comment by RockyTheProtogen** [comment]
> > > The following required packages were not found:
> > > gtksourceviewmm-3.0
> 
> Where can i get this package I ran the script 3-4 times

I installed [the package](https://archlinux.org/packages/extra/x86_64/gtksourceviewmm/) and it doesn't seem to change the result.

**Comment by DynamisOp** [comment]
> > > > The following required packages were not found:
> > > > gtksourceviewmm-3.0
> > 
> > 
> > Where can i get this package I ran the script 3-4 times
> 
> I installed [the package](https://archlinux.org/packages/extra/x86_64/gtksourceviewmm/) and it doesn't seem to change the result.

+1

**Comment by DynamisOp** [comment]
Nvm guyz i got the solution 
https://github.com/end-4/dots-hyprland/issues/955
