### ISSUE TITLE
Waybar is not shown

### ISSUE THREAD

**Issue by Cyr3ss** [koeqaife/hyprland-material-you#139]
I have an issue. All binds are working fine, maybe except a bind that shows other binds, but I have no waybar at all! I think there is no script that configure start up of waybar. All packets are installed, there is no problem with that

**Comment by koeqaife** [comment]
there's no waybar

**Comment by jkhill5** [comment]
Then how to put cava on the top bar

**Comment by koeqaife** [comment]
Idk
