### ISSUE TITLE
i got this error ags not working

### ISSUE THREAD

**Issue by jayadeep11** [koeqaife/hyprland-material-you#142]
➜  ~ ags

(com.github.Aylur.ags:989): Gjs-Console-CRITICAL **: 20:59:26.449: 12 | import {} from "apps/settings/main.ts";
                    ^
error: Could not resolve: "apps/settings/main.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:12:16

13 | import {} from "apps/emoji/main.ts";
                    ^
error: Could not resolve: "apps/emoji/main.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:13:16

14 | import { cheatsheet } from "modules/cheatsheet.ts";
                                ^
error: Could not resolve: "modules/cheatsheet.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:14:28

16 | import { popups } from "modules/popups.ts";
                            ^
error: Could not resolve: "modules/popups.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:16:24

17 | import { start_battery_warning_service } from "services/battery_warning.ts";
                                                   ^
error: Could not resolve: "services/battery_warning.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:17:47

19 | import { calendar } from "modules/calendar.ts";
                              ^
error: Could not resolve: "modules/calendar.ts". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:19:26

21 | import configuration from "services/configuration";
                               ^
error: Could not resolve: "services/configuration". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:21:27

22 | import { custom_theme, ThemeJson } from "variables";
                                             ^
error: Could not resolve: "variables". Maybe you need to "bun install"?
    at /home/jaya/dotfiles/ags/main.ts:22:41
^[[57361u

**Comment by koeqaife** [comment]
hmm

**Comment by koeqaife** [comment]
you have to run agsv1 not ags

**Comment by jayadeep11** [comment]
ok now it works!
