### ISSUE TITLE
Screen blink after install

### ISSUE THREAD

**Issue by the-merky** [koeqaife/hyprland-material-you#144]
Hi! First of all, I just want to thank you for these dotfiles, have been a fan of Material 3 and have attempted the same thing as you(and failed). I made a fresh install of CachyOS(Arch Based) And ran your install script. The script did not encounter many issues, only one with Vencord due to discord not being installedone with Microtex, and something with the wallpaper(which I think I can fix). However after restarting my PC, I do get a nicer SDDM but Hyprland is on its "default autogenerated config file". I manually copied the config files from the dotfiles after running the install script a couple of times. The widgets seem to load, but no wallpaper and when I move my cursor the screen blinks,turns black and after a few seconds turns on again and the same process repeats. I did this whole process a couple of times. Maybe I should mention that I first installed the CachyOS Hyprland preset, although I don't think this would cause issues.

**Comment by koeqaife** [comment]
I honestly don't know what the problem is, what kind of video card do you have?

**Comment by the-merky** [comment]
I have a Radeon 6700XT. I have experienced this issue with COSMIC before, It just mysteriously went away after a reinstall.

**Comment by koeqaife** [comment]
And you can also try configuring monitors in .config/hypr/conf/custom/monitors.conf

**Comment by the-merky** [comment]
Thanks, will try the monitor and then create an issue. Currently on holiday, will get back to this on the 28th.

**Comment by the-merky** [comment]
Update: I installed Gnome and gdm to be able to check logs and experiment. I encountered a very interesting issue: When starting in Gnome, logging out and starting Hyprland,the blinking continues even after logging out of Hyprland and is even present in GDM and Gnome on Xorg.

**Comment by koeqaife** [comment]
Hmmm it's very weird

**Comment by the-merky** [comment]
I'm pretty sure that it has to do with the startup scripts. Will investigate further.

**Comment by the-merky** [comment]
Unsure about the cause, will archive this for now.
