### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by JoseMRodriguezM** [koeqaife/hyprland-material-you#26]
Hello, I'm curious on how to put the main bar on the bottom of my screen? Is that possible? and another thing is that I made some modifications in the ~/.config/hypr files, I modified my keyboard layout, and some of the windows options and now every time I start my pc appears this notification:

![image](https://github.com/koeqaife/hyprland-material-you/assets/76118394/3bdcedef-2acb-4023-a989-8863600db5c8)

How can I delete that notification or what can I do?

**Comment by S4NKALP** [comment]
edit anchor  located in  line 487 in ~/dotfiles/ags/modules/bar.ts

**Comment by JoseMRodriguezM** [comment]
Nice, thanks for the help!
