### ISSUE TITLE
too many duplicate processes !?

### ISSUE THREAD

**Issue by paixeww** [koeqaife/hyprland-material-you#28]
![image](https://github.com/koeqaife/hyprland-material-you/assets/62608119/c062011a-8204-4f47-bcfa-2dc0332dfc32)

There is like 4 screenful more processes that I could not fit in my screen.

brightness.sh is located at dotfiles/ags/scripts
busctl gets the rs.wl.gammarelay Brightness
awk 's description is awk {print $2}

wl-gammarelay is outdated and last time I checked it was using 10% of the CPU, idk why.
wl-gammarelay-rs is the updated version. I do not know how hard it would be to upgrade the package with your current configurations but I recommend upgrading it.

**Comment by paixeww** [comment]
logging out and logging in again might be the cause, I am not really sure. Checking if there is a running process if not, then executing the script would be a solution.

**Comment by koeqaife** [comment]
I'll try to make a fix later

**Comment by koeqaife** [comment]
and I don't have any problems hah
