### ISSUE TITLE
ags package.json missing file

### ISSUE THREAD

**Issue by gudkovWay** [koeqaife/hyprland-material-you#33]
npm error syscall open
npm error path /home/q/.config/ags/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/q/.config/ags/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/q/.npm/_logs/2024-07-14T13_39_28_385Z-debug-0.log

**Comment by koeqaife** [comment]
Can you give us more information? What are you talking about?

**Comment by koeqaife** [comment]
why are you using npm?

**Comment by gudkovWay** [comment]
bcs ags required js?

**Comment by koeqaife** [comment]
This is AGS's problem, not mine, create an issue not here

**Comment by gudkovWay** [comment]
u wanna say u use ags without install local packages for js in the .config/ags dir?

**Comment by koeqaife** [comment]
ags it's gjs

**Comment by koeqaife** [comment]
not just js

**Comment by koeqaife** [comment]
so you need to install GJS and not npm or something like this

**Comment by koeqaife** [comment]
TypeError: this._device is undefined is error with network service in AGS and I can't do anything about it
