### ISSUE TITLE
Errors in config and black screen

### ISSUE THREAD

**Issue by realgamebreaker** [koeqaife/hyprland-material-you#35]
I installed the hyprland preset with archinstall and installed this theme. Whenever I log in or start Hyprland I get a black screen and an error (as seen in the picture
![image](https://github.com/user-attachments/assets/b20c852a-bd15-4c33-90c9-2718ffdca19f)

**Comment by koeqaife** [comment]
isn't VM?

**Comment by koeqaife** [comment]
Try running ~/dotfiles/plugins.sh and then hyprctl dispatch exec ags, if you installed everything correctly and it's not a VM it should work

**Comment by realgamebreaker** [comment]
> Try running ~/dotfiles/plugins.sh and then hyprctl dispatch exec ags, if you installed everything correctly and it's not a VM it should work

That fixed it but plugins.sh was missing the executable flag and when I added it I got a message that ~/dotfiles has been modified and I will not get updates

**Comment by koeqaife** [comment]
you can use git pull && ~/dotfiles/after_update.sh later after update

**Comment by koeqaife** [comment]
to disable auto-update remove

exec-once = ~/dotfiles/scripts/update_timer.sh

in dotfiles/hypr/conf/autostart.conf

**Comment by dnlfurtek** [comment]
Had similar error, but without warnings, just black screen, and most keybindings didn't work. This is how I fixed it:
uninstall
run install.sh
after prompt for MicroTex remove wal from .config (MicroTeX creates wal directory)
finish install
reboot
(still no warnings and only black screen)
run ~/dotfiles/plugins.sh and then run hyperctl dispatch exec ags
Then it worked. Auto-updates work, everything runs smoothly.

**Comment by realgamebreaker** [comment]
> Had similar error, but without warnings, just black screen, and most keybindings didn't work. This is how I fixed it: uninstall run install.sh after prompt for MicroTex remove wal from .config (MicroTeX creates wal directory) finish install reboot (still no warnings and only black screen) run ~/dotfiles/plugins.sh and then run hyperctl dispatch exec ags Then it worked. Auto-updates work, everything runs smoothly.

But how could you run plugins.sh, it was missing the executable flag for me and I had to add it, and because I „modified“ it, the branch was out of sync
