### ISSUE TITLE
Error: directory [...] already exists in config

### ISSUE THREAD

**Issue by FullStackPete** [koeqaife/hyprland-material-you#39]
I run the commands on my freshly installed arch and each time I get this error after I get asked to install MicroTex and I agree. First it was directory "wal" which I removed from .config and now it's directory "hypr". Should I just keep removing the directories after each time I run install.sh until it resolves?

**Comment by koeqaife** [comment]
you should either backup or delete these folders, the script makes links to folders to ~/dotfiles so it's ok if you delete links in ~/.config

**Comment by paixeww** [comment]
#52
