### ISSUE TITLE
Error setting colors during installation

### ISSUE THREAD

**Issue by axelyamel01** [koeqaife/hyprland-material-you#40]
I tried the install.sh command and it fails with the following error:

```
:: Setting colors
Traceback (most recent call last):
  File "/home/axel/dotfiles/material-colors/generate.py", line 7, in <module>
    from materialyoucolor.quantize import QuantizeCelebi  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'materialyoucolor'
```

Then I get the message:

```
Config error in file /home/USER/dotfiles/hypr/hyprland.conf at line 34: source= globbing error: found no match
```

The colors are all transparent now. I attached a picture. Also, I just ran ./install.sh and followed on-screen selections.

![20240716_102002](https://github.com/user-attachments/assets/24b4dfb4-6ca3-4009-992f-8e0f0e778e71)

**Comment by koeqaife** [comment]
install python-materialyoucolor package
