### ISSUE TITLE
i am getting this error 3rd time, what to do???

### ISSUE THREAD

**Issue by progb4atys** [koeqaife/hyprland-material-you#42]
![IMG_20240717_124102](https://github.com/user-attachments/assets/07d12f51-417e-4cac-b5b0-2c2bdc5e3313)

Config error in file /home/user/dotfiles/conf/keybinding.conf at line 99: invalid dispatcher, requested "hyprexpo:expo" doesnt exist

**Comment by Tomas2p** [comment]
do `hyprpm update` and if necessary, install the plugin `hyprexpo` manually

**Comment by koeqaife** [comment]
try run ~/dotfiles/plugins.sh

**Comment by progb4atys** [comment]
![IMG_20240717_213034](https://github.com/user-attachments/assets/cd2a62e5-ab8b-47f9-8906-bee855a54a9b)


Still getting this black screen instead of any wallpaper how to fix this??

**Comment by koeqaife** [comment]
You have to change your wallpaper

**Comment by koeqaife** [comment]
Open the right sidebar and then open settings
