### ISSUE TITLE
Getting text instead of icons 

### ISSUE THREAD

**Issue by Chaitran77** [koeqaife/hyprland-material-you#43]
Can't figure out why I'm getting text instead of icons pretty much everywhere.

![image](https://github.com/user-attachments/assets/309a5cdc-ee9c-4524-915e-c180c80293bb)
![image](https://github.com/user-attachments/assets/b8a692c6-4761-475b-96e2-575a17dcc1eb)

**Comment by Chaitran77** [comment]
Perfect, that worked! You may want to check the install script, I don't know why it wasn't installed during the setup.

**Comment by koeqaife** [comment]
> Perfect, that worked! You may want to check the install script, I don't know why it wasn't installed during the setup.

I checked it should install
