### ISSUE TITLE
Can't start AGS/UI 

### ISSUE THREAD

**Issue by erlonbie** [koeqaife/hyprland-material-you#48]
Hey, I saw your reddit post and decided to try it, nice job btw!

The problem that I'm having is that AGS shows a red bar (as if was an error) right at the beginnig and it disappears.

I searched a bunch of issues before posting this, so I have no idea how to solve it.

I installed bun, ags (following this [doc](https://aylur.github.io/ags-docs/config/installation/)), hyprpm is up to date and plugins installed.

hyprctl dispatch exec ags returns "ok" but nothing happens, I don't know how to run in a verbose way to debug it.

Any clue?

**Comment by koeqaife** [comment]
Run killall ags && ags and show me

**Comment by erlonbie** [comment]
(com.github.Aylur.ags:101866): Gjs-Console-CRITICAL **: 17:03:06.596: Error: Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://GnomeBluetooth/?version=3.0:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

**Comment by erlonbie** [comment]
I don't have gnome installed, do I need to? I run plasma, proabably would not be a good idea

**Comment by Chaitran77** [comment]
How did you get on? I would recommend having a look through my issues (couple closed now) because it sounds like you might run in to issues similar to mine... GL!
