### ISSUE TITLE
Don't block input when AGS panes/windows are open

### ISSUE THREAD

**Issue by Chaitran77** [koeqaife/hyprland-material-you#51]
Currently, when a side pane or window such as the settings are opened, keyboard input is blocked to the rest of the Hyprland interface (looks like mouse input works). This would be okay if the rest of the interface was dimmed/shadowed but it is not. I think this is good because I would like to be able to interact with other windows whilst these AGS interfaces are open. 

Also, escape to close a pane doesn't always work - one scenario is when one side pane is opened and then the other one is without closing the first one. Pressing escape does close the second one but leaves the first open. It should either close both of them or each one respectively. I think this is however related to the input blocking issue above and has something to do with the AGS windows being not being in focus by the mouse.

The open side pane buttons don't respond to quick inputs either - if I click to open but was to close it shortly after, it won't work by clicking the button again unless I move the mouse a bit (it seems I have to move the mouse, waiting doesn't work).

**Comment by Chaitran77** [comment]
It might also be nice if the search input for the apps is autofocused when it is shown.

**Comment by koeqaife** [comment]
If do that, entry won't work there

**Comment by Chaitran77** [comment]
Would you be able to fix the other things to at least make it flow better?
