### ISSUE TITLE
Timeout error when installing sensors

### ISSUE THREAD

**Issue by TacShot** [koeqaife/hyprland-material-you#53]
![17213829797958829645527066382936](https://github.com/user-attachments/assets/f905358a-85ad-4e5c-bc3b-d699f4e7fdcd)
After installing microtex, I went on to install sensors and boom there's a timeout error.
Later It  tells me there's a wal directory in .config so I go to /hyprland/config and then I just

rmdir -R wal

 go back to dotfiles
./install.sh 

and the cycle repeats

I know I suck at this but I'm willing to learn and fix issues

**Comment by koeqaife** [comment]
#52

**Comment by koeqaife** [comment]
Now there won't be such a problem
