### ISSUE TITLE
Let people change their hyprland configuration without blocking updates

### ISSUE THREAD

**Issue by realgamebreaker** [koeqaife/hyprland-material-you#54]
I only changed my keyboard layout, some keybindings, my monitor configuration to adjust the scale and added one window rule to hyprland.conf.
This prvents me from updating

dotfiles on  main [!⇣] 
❯ ./update.sh 
:: Cannot update: Changes detected in files.
:: You can write "$ git diff-index --name-only HEAD --" to see which files have changed

dotfiles on  main [!⇣] 
❯ git diff-index --name-only HEAD --
hypr/conf/input.conf
hypr/conf/keybinding.conf
hypr/conf/monitor.conf
hypr/hyprland.conf

**Comment by koeqaife** [comment]
I created custom.conf so people can change the hyprland configuration

**Comment by koeqaife** [comment]
You can use `git pull` and then `~/dotfiles/setup/after_update.sh` to update the config
