### ISSUE TITLE
AGS Critical Error - this._device is undefined

### ISSUE THREAD

**Issue by jgroboredo** [koeqaife/hyprland-material-you#58]
Hi,

First of all, thanks a lot for your dotfiles.

I took some interest in ags recently and I enjoyed your ags configuration quite a lot.

I'm trying to get ags working on my machine. I've copied the ags folder from your dotfiles to `~/.config` and, every time I launch it I get the following error logs:

```
(com.github.Aylur.ags:59585): Gjs-Console-CRITICAL **: 23:26:52.510: TypeError: this._device is undefined
scan@resource:///com/github/Aylur/ags/service/network.js:107:9
WifiScan@file:///tmp/ags/js/main.js:24:16
startPoll/this._interval<@resource:///com/github/Aylur/ags/variable.js:46:34
interval@resource:///com/github/Aylur/ags/utils/timeout.js:3:5
startPoll@resource:///com/github/Aylur/ags/variable.js:45:30
Variable@resource:///com/github/Aylur/ags/variable.js:26:18
default@resource:///com/github/Aylur/ags/variable.js:130:36
@file:///tmp/ags/js/main.js:73:27
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
``` 

I've searched through the closed issues and I think someone has mentioned a similar problem, which was marked as being an "ags" issue. Although I have little to 0 experience with ags, this feels more like a misconfiguration on my part (note that I haven´t installed the dotfiles using your scripts, since I'm solely interested in the ags configuration), rather than a problem with ags itself.

Any help here would be appreciated. I'd be happy to provide some more logs or debug information.

I'm running arch on 6.10.0-arch1-2.

**Comment by koeqaife** [comment]
do you have networkmanager installed? And do you run arch on a real pc (not on a VM)?

**Comment by jgroboredo** [comment]
Thanks for your reply.

I do have networkmanager installed and it's running baremetal, yes.

I tried copying directly the ags folder from one of the projects that you refer, namely [end-4](https://github.com/end-4/dots-hyprland/), and it worked out of the box.

**Comment by koeqaife** [comment]
idk why

**Comment by koeqaife** [comment]
try delete lines 28-30
> 
const _scan_timer = Variable(undefined, {
    poll: [15000, WifiScan]
});

in dotfiles/ags/settings/network.ts
