### ISSUE TITLE
ags crashes after closing leftside menu

### ISSUE THREAD

**Issue by AkhilGuddati** [koeqaife/hyprland-material-you#65]
![image](https://github.com/user-attachments/assets/db9cb904-223b-49c3-a97a-7cd7aeb740bd)

AGS completely crashes after opening and closing the left side menu (left side menu is fully functional when its open).
Crash happens when the the gemini widget is enabled irrespective of which menu was last shown, 
when the gemini widget is disabled from the left side menu it works fine.

**Comment by koeqaife** [comment]
it's hyprland problem

**Comment by koeqaife** [comment]
https://github.com/Aylur/ags/issues/522
try updating ags
