### ISSUE TITLE
Strange window/app spawning behaviour

### ISSUE THREAD

**Issue by gervasetuxworth** [koeqaife/hyprland-material-you#66]
Previously was working fine, but after updating using your update.sh script today, some strange behaviors have started.

- If i launch the terminal, it always works correctly (the terminal window is spawned on the monitor/workspace that the mouse is on)
- If I launch Nautilus, the window spawns correctly, but the mouse is automatically moved to 0,0 (workspace 2, monitor 2).
- If I launch firefox, the FIRST firefox instance opens in the correct place, but each subsequent one is spawned on workspace 2/monitor 2, regardless of where the mouse is. As above, the mouse is snapped to 0,0 on 2nd and onward Firefox window
- VS Code always spawns on workspace2/monitor2. Mouse is again snapped to 0,0

I have a feeling that the mouse being moved is what is causing the incorrect spawning. 

Any ideas?

**Comment by gervasetuxworth** [comment]
This may be caused by the switch to hyprland-git

https://github.com/hyprwm/Hyprland/issues/7089

**Comment by S4NKALP** [comment]
obviously you will get bug in git version 


but it working fine in stable version

**Comment by NotAF0e** [comment]
Perhaps warn about hyprland-git in the readme?

**Comment by koeqaife** [comment]
You can install hyprland now, but the plugins may not work
