### ISSUE TITLE
Clipboard History doesn't render characters properly

### ISSUE THREAD

**Issue by dalmatheo** [koeqaife/hyprland-material-you#76]
Hello everyone, I've been using hyprland-material-you for a day and I'm very happy with it. However, I have a problem with the clipboard history, some characters such as "┃" doesn't render properly, and when I'm bulk copying characters it's kinda annoying to not know what I select in the clipboard.

![image](https://github.com/user-attachments/assets/34f68c53-d84e-4272-a0c6-8709dd2693cf)

**Comment by dalmatheo** [comment]
I installed the fonts to see the character after installing hyprland-material-you, is there a way to rebuild just the clipboard manager?

**Comment by koeqaife** [comment]
it seems that this symbol is not in the fonts I'm currently using

**Comment by koeqaife** [comment]
or it's an ags problem
