### ISSUE TITLE
Can't update / Don't know how to

### ISSUE THREAD

**Issue by dalmatheo** [koeqaife/hyprland-material-you#79]
Hello, so I tried to execute:
`./update.sh` in the dotfiles folder to update the hyprland material you. It prompted me an error saying that:
`Cannot update: Changes detected in files.
:: You can write "$ git diff-index --name-only HEAD --" to see which files have changed
:: use --force to ignore changes`
I tried to use `./update.sh --force` to continue but it prompted me with an error:
`error: Your local changes to the following files would be overwritten by merge:
	hypr/conf/custom.conf
	hypr/conf/input.conf
Please commit your changes or stash them before you merge.
Aborting`

I don't really know how to fix that, even tho I'm prettier it's because I edited some keybinds in the input.conf instead of custom.conf

**Comment by koeqaife** [comment]
`git reset --hard origin/main`
and then use update.sh

**Comment by dalmatheo** [comment]
error: Entry 'hypr/conf/custom.conf' not uptodate. Cannot merge.
fatal: Could not reset index file to revision 'origin/main'.

**Comment by dalmatheo** [comment]
I did that to fix it:
git update-index --really-refresh
