### ISSUE TITLE
Can't edit custom.conf

### ISSUE THREAD

**Issue by dalmatheo** [koeqaife/hyprland-material-you#80]
When I add that to my custom.conf in hypr/conf:
`input {
    kb_layout = fr
    kb_variant = 
    kb_model =
    kb_options = grp:alt_shift_toggle 
    numlock_by_default = true
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
    sensitivity = 0 
}`

it prompt me with an error
![image](https://github.com/user-attachments/assets/1544ac15-361a-4791-b53c-4a2dd0914bc6)

**Comment by koeqaife** [comment]
hypr/custom.conf doesn't exists after update, move everything from there to files in hypr/custom/

**Comment by dalmatheo** [comment]
So I have to create .conf files inside of hypr/custom? Will they automatically be added in hyprland.conf or do I have to do it?

**Comment by koeqaife** [comment]
run update.sh

**Comment by dalmatheo** [comment]
colors-hyprland.conf doesn't exist

**Comment by koeqaife** [comment]
try to reboot pc =\

**Comment by dalmatheo** [comment]
Didn't work I checked

**Comment by koeqaife** [comment]
> colors-hyprland.conf doesn't exist

show me an error

**Comment by dalmatheo** [comment]
Fixed on reboot, my bad
