### ISSUE TITLE
Black screen and errors in config

### ISSUE THREAD

**Issue by leondonjon** [koeqaife/hyprland-material-you#89]
![IMG_20240809_002712_155](https://github.com/user-attachments/assets/d6db6252-d4be-45aa-81cd-b23c3f5a8d42)
I have errors in config, how fix it?

**Comment by S4NKALP** [comment]
set the wallpaper

**Comment by leondonjon** [comment]
> set the wallpaper

`python` ~/dotfiles/hypr/scripts/wallpaper.py -RTraceback (most recent call last):File "/home/leondonjon/dotfiles/hypr/scripts/wallpaper.py", line 75, in <module>spec.loader.exec_module(GENERATOR) # type: ignore^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "<frozen importlib._bootstrap_external>", line 995, in exec_moduleFile "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removedFile "/home/leondonjon/dotfiles/material-colors/generate.py", line 7, in <module>from materialyoucolor.quantize import QuantizeCelebi # type: ignore^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ModuleNotFoundError: No module named 'materialyoucolor'.`

**Comment by S4NKALP** [comment]
install python-materialyoucolor-git

**Comment by leondonjon** [comment]
> install python-materialyoucolor-git

I installed it, is there anything else I need to do?

**Comment by leondonjon** [comment]
> > install python-materialyoucolor-git
> 
> I installed it, is there anything else I need to do?

After installing and running the script with the wallpaper, it didn't find swww, I installed it, but it still doesn't find it

**Comment by leondonjon** [comment]
> > > install python-materialyoucolor-git
> > 
> > 
> > I installed it, is there anything else I need to do?
> 
> After installing and running the script with the wallpaper, it didn't find swww, I installed it, but it still doesn't find it

I install swww, now the config error does not appear, but the screen is still dark

**Comment by leondonjon** [comment]
> > > > install python-materialyoucolor-git
> > > 
> > > 
> > > I installed it, is there anything else I need to do?
> > 
> > 
> > After installing and running the script with the wallpaper, it didn't find swww, I installed it, but it still doesn't find it
> 
> I install swww, now the config error does not appear, but the screen is still dark

I install bun, gnome-bluetooth and brightnessctl, and its working, but it's looking so ugl, i would like reinstall it

I close this issue
