### ISSUE TITLE
Missing Localisatio0n/Icons?

### ISSUE THREAD

**Issue by Madcliff** [koeqaife/hyprland-material-you#91]
I have been trying to install this on an Arch without replacing my own Hypr configs. 

I can get the ags bars to show up, and the colour schemes, but I then experience very weird behavour. It looks like missing icons. this tends to mean that every text box in the UI has something like battery_90% preceeeding it.

**Comment by S4NKALP** [comment]
did you install fontss??

**Comment by Madcliff** [comment]
I have tried installing a bunch of different fonts yes

**Comment by Madcliff** [comment]
This is how everything is looking like. 

![2024-08-11-150410_hyprshot](https://github.com/user-attachments/assets/e0d26125-586c-4915-a645-32e806ab7cdd)

**Comment by koeqaife** [comment]
install ttf-material-symbols-variable-git from AUR

**Comment by Madcliff** [comment]
Ah thankyou that fixed it!
