### ISSUE TITLE
The Hyprland isn't opening after dotfile installation 

### ISSUE THREAD

**Issue by PSGitHubUser1** [koeqaife/hyprland-material-you#99]
I just successfully installed Hyprland & this dotfile, rebooted too and stuck on SDDM (Candy/Corner).

On press <kbd>Enter</kbd> after entering my password. The screen goes black and SDDM opens again.

And I don't know how to reinstall dotfile as I don't know which packages shoud I remove to make a 'fresh install'

> Note: I used ML4W Dotfile before but I liked this one more

**Comment by koeqaife** [comment]
Try to run hyprland from tty

**Comment by PSGitHubUser1** [comment]
not working

**Comment by koeqaife** [comment]
show me error =\

**Comment by PSGitHubUser1** [comment]
theres no error

I just enter my password and press <kbd>Enter</kbd> and screen goes black for few seconds and at last, again the login screen comes (sddm)

**Comment by PSGitHubUser1** [comment]
> show me error =\

on tty typing Hyprland does nothing

**Comment by koeqaife** [comment]
so I can't help you =\

**Comment by PSGitHubUser1** [comment]
theres no error

I just enter my password and press <kbd>Enter</kbd> and screen goes black for few seconds and at last, again the login screen comes (sddm)

k bro :( 👍

**Comment by PSGitHubUser1** [comment]
> then I can't help you =\

k bro 👍 :(
